# Worksheet 04

Name: Risheet Nair 
UID: U87299654

### Topics

- Distance & Similarity
- Cost Functions
- K means

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

d is the dimension of the vector space(each vector is represented by 10 values)<br>
p is a parameter to make the distance function more flexible(basically a way to parametrize the function)

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

The Euclidean distance is essentially just the shortest distance between points and is usually depicted by a straight line.<br>
The Manhattan distance is the sum of all the line distances between points. With the Manhattan distance, we cannot go diagonally. Instead we must always follow the grid lines to calculate our distance.

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

When p is very large, the distance will get closer and closer to 1.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

No. There is a counterexample in which point $A=(0,0)$, $B=(1,0)$, $C=(0,1)$. If $p < 1$, then $D(B,C) = 2^{1/p}$ which would result in a distance greater than $2$. So $D(B, C) > D(B, A) + D(A, C)$ which violates the triangle inequality.

e) when would you use cosine similarity over the euclidan distance?

We use cosine similarity over Euclidean distance when the direction of the vector(s) matters more than the magnitude.

f) what does the jaccard distance account for that the manhattan distance doesn't?

The Jaccard distance accounts for the size of the intersection between say 2 documents $x$ and $y$ whereas Manhattan distance would not be able to distinguish between the set differences.

#### Part 2

Consider the following two sentences:

In [1]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [2]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [3]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['hello', 'Alice', 'Bob', 'name', 'my', 'is']
[1, 1, 0, 1, 1, 1]


Let's add a new sentence to our corpus:

In [4]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [5]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['hello', 'Alice', 'Bob', 'name', 'Claude', 'my', 'is', 'hi']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [6]:
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

v2 = [1 if x in s2 else 0 for x in all_words]
print(v2)

v3 = [1 if x in s3 else 0 for x in all_words]
print(v3)


[1, 1, 0, 1, 0, 1, 1, 0]
[1, 0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 1, 1, 1, 1, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [10]:
def manhattan_distance(v1, v2):
    zipped_vecs = zip(v1, v2)
    return sum(abs(x1 - x2) for x1, x2 in zipped_vecs)
    # res = 0
    # for i in range(len(v1)):
    #     res += abs(v1[i] - v2[i])
        
    # return res


print('Distance between v1 and v2:', manhattan_distance(v1, v2))
print('Distance between v2 and v3:', manhattan_distance(v2, v3))
print('Distance between v1 and v3:', manhattan_distance(v1, v3))

Distance between v1 and v2: 2
Distance between v2 and v3: 4
Distance between v1 and v3: 4


$v1$ and $v2$ are most similar as the distance is the smallest.

d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [12]:
import numpy as np

s4 = "hi Alice"
corpus.append(s4)
v4 = [1 if x in s4 else 0 for x in all_words]

s5 = "hello Claude"
corpus.append(s5)
v5 = [1 if x in s5 else 0 for x in all_words]

s6 = "Bob my name is Claude"
corpus.append(s6)
v6 = [1 if x in s6 else 0 for x in all_words]

s7 = "hi Claude my name is Alice"
corpus.append(s7)
v7 = [1 if x in s7 else 0 for x in all_words]

s8 = "hello Bob"
corpus.append(s8)
v8 = [1 if x in s8 else 0 for x in all_words]

matrix = []
matrix.append(v1)
matrix.append(v2)
matrix.append(v3)
matrix.append(v4)
matrix.append(v5)
matrix.append(v6)
matrix.append(v7)
matrix.append(v8)

matrix = np.array(matrix)
print(matrix)


[[1 1 0 1 0 1 1 0]
 [1 0 1 1 0 1 1 0]
 [0 0 0 1 1 1 1 1]
 [0 1 0 0 0 0 0 1]
 [1 0 0 0 1 0 0 0]
 [0 0 1 1 1 1 1 0]
 [0 1 0 1 1 1 1 1]
 [1 0 1 0 0 0 0 0]]


e) How many rows and columns does this matrix have?

In [13]:
print(matrix.shape)

(8, 8)


f) When using the Manhattan distance, which two sentences are the most similar?

In [15]:
lowest_dist = manhattan_distance(v1, v2)
most_similar = (1, 2)

for i in range(1, 9):
    for j in range(i + 1, 9):
        if manhattan_distance(matrix[i - 1], matrix[j - 1]) < lowest_dist:
            lowest_dist = manhattan_distance(matrix[i - 1], matrix[j - 1])
            most_similar = (i, j)
            
print('The most similar sentences are sentence', str(most_similar[0]), 'and sentence', str(most_similar[1]))


The most similar sentences are sentence 3 and sentence 7


### Cost Function

Solving Data Science problems often starts by defining a metric with which to evaluate solutions were you able to find some. This metric is called a cost function. Data Science then backtracks and tries to find a process / algorithm to find solutions that can optimize for that cost function.

For example suppose you are asked to cluster three points A, B, C into two non-empty clusters. If someone gave you the solution `{A, B}, {C}`, how would you evaluate that this is a good solution?

Notice that because the clusters need to be non-empty and all points must be assigned to a cluster, it must be that two of the three points will be together in one cluster and the third will be alone in the other cluster.

In the above solution, if A and B are closer than A and C, and B and C, then this is a good solution. The smaller the distance between the two points in the same cluster (here A and B), the better the solution. So we can define our cost function to be that distance (between A and B here)!

The algorithm / process would involve clustering together the two closest points and put the third in its own cluster. This process optimizes for that cost function because no other pair of points could have a lower distance (although it could equal it).

### K means

a) (1-dimensional clustering) Walk through Lloyd's algorithm step by step on the following dataset:

`[0, .5, 1.5, 2, 6, 6.5, 7]` (note: each of these are 1-dimensional data points)

Given the initial centroids:

`[0, 2]`

**1st Iteration**:<br>
Initial 2 centroids : `[0, 2]`<br>
Cluster 1: `[0, 0.5]`<br>
Cluster 2: `[1.5, 2, 6, 6.5, 7]`<br>
New Center 1: $0.25$<br>
New Center 2: $4.6$<br><br>

**2nd Iteration**:<br>
Centroids : `[0.25, 4.6]`<br>
Cluster 1: `[0, 0.5, 1.5, 2]`<br>
Cluster 2: `[6, 6.5, 7]`<br>
New Center 1: $1$<br>
New Center 2: $6.5$<br><br>

**3rd Iteration**:<br>
Centroids : `[1, 6.5]`<br>
Cluster 1: `[0, 0.5, 1.5, 2]`<br>
Cluster 2: `[6, 6.5, 7]`<br>
New Center 1: $1$<br>
New Center 2: $6.5$<br><br>

There was no change so we're done with centroids `{1, 6.5}` and clusters `[0, 0.5, 1.5, 2]` and `[6, 6.5, 7]`

b) Describe in plain english what the cost function for k means is.

The cost function of k means is the squared distance of all the points in a cluster to their closest centroid. The goal is to minimize this cost.

c) For the same number of clusters K, why could there be very different solutions to the K means algorithm on a given dataset?

There could be different solutions because of the initial centroids that are selected. Since the selection of the initial centroids is random, it's very possible for the algorithm to come up with different solutions even on the same dataset.

d) Does Lloyd's Algorithm always converge? Why / why not?

Lloyd's Algorithm will always converge as it is a greedy algorithm and eventually, it will reach a solution. The caveat is it is not guaranteed to find the global minimum(optimal solution) because of its greedy approach.